# Copy to /etc/nginx/sites-available/play.ivplayer.tr
# DNS: play.ivplayer.tr A → 78.189.53.159  then certbot --nginx -d play.ivplayer.tr
# Same Node process as license.ivplayer.tr; player lives at /app/
server {
    listen 80;
    listen [::]:80;
    server_name play.ivplayer.tr;

    location = / {
        return 302 /app/;
    }

    location / {
        proxy_pass http://127.0.0.1:8787;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }
}
